export interface ChecklistQuestion {
	id: string;
	html: string;
}

export interface ChecklistSection {
	title: string;
	collapsed?: boolean;
	questions: ChecklistQuestion[];
}

export const LLM_CHECKLIST: ChecklistSection[] = [
	{
		title: "Phase 0: Purpose, Scope, and Success Criteria",
		questions: [
			{ id: "p0q0", html: "Which use cases must this support: chat, coding help, document Q&A, image generation, or something else?" },
			{ id: "p0q1", html: "Confirmed: inference only, using pre-trained downloaded models -> no training, no fine-tuning. Is that still accurate?" },
			{ id: "p0q2", html: "Who are the exact four users, and what devices will each use?" },
			{ id: "p0q3", html: "Will any user need more than one device connected under their single key?" },
			{ id: "p0q4", html: "Will access be private-only (family via VPN/mesh) or exposed as a public URL?" },
			{ id: "p0q5", html: "What response speed (tokens per second) is acceptable to the family?" },
			{ id: "p0q6", html: "What time-to-first-response is acceptable?" },
			{ id: "p0q7", html: "How many of the four users might realistically use it at the same time?" },
			{ id: "p0q8", html: "What maximum context length (conversation/document size) is required?" },
			{ id: "p0q9", html: "What availability is expected -> occasional use, or always-on reliability?" },
			{ id: "p0q10", html: "What kind of data will family members send it (personal, financial, medical, schoolwork)?" },
			{ id: "p0q11", html: "What would make this project a success?" },
			{ id: "p0q12", html: "What would make it not worth continuing?" },
		],
	},
	{
		title: "Phase 1: Budget, Procurement, and Ownership",
		questions: [
			{ id: "p1q0", html: "What is the maximum upfront hardware budget?" },
			{ id: "p1q1", html: "What is the maximum acceptable monthly running cost (electricity plus subscriptions)?" },
			{ id: "p1q2", html: "What is the estimated annual electricity cost at idle, typical, and peak load?" },
			{ id: "p1q3", html: "Prebuilt system or self-assembled?" },
			{ id: "p1q4", html: "Are the required components available in your country?" },
			{ id: "p1q5", html: "Does the warranty allow continuous 24/7 operation?" },
			{ id: "p1q6", html: "Is local warranty/repair service available?" },
			{ id: "p1q7", html: "Can the system be returned if real-world model speed is disappointing?" },
			{ id: "p1q8", html: "Would renting cloud GPU time be cheaper for your family's actual usage level?" },
			{ id: "p1q9", html: "What is the exit/resale plan if you abandon the project?" },
		],
	},
	{
		title: "Phase 2: Physical Space, Power, and Environment",
		questions: [
			{ id: "p2q0", html: "What hardware form factor fits your available space?" },
			{ id: "p2q1", html: "Where exactly will the machine live?" },
			{ id: "p2q2", html: "Is that location safe from spills, pets, children, and dust?" },
			{ id: "p2q3", html: "What are the machine's idle, typical, and peak power draws?" },
			{ id: "p2q4", html: "Can the electrical circuit sustain continuous load?" },
			{ id: "p2q5", html: "What else shares that circuit (microwave, vacuum, space heater)?" },
			{ id: "p2q6", html: "Is a dedicated circuit needed?" },
			{ id: "p2q7", html: "Is surge protection needed?" },
			{ id: "p2q8", html: "Is a UPS needed, and what runtime?" },
			{ id: "p2q9", html: "Can the UPS signal the OS to shut down gracefully on battery?" },
			{ id: "p2q10", html: "Will the machine restart automatically after power returns?" },
			{ id: "p2q11", html: "How much heat will it add to the room?" },
			{ id: "p2q12", html: "Will it need extra ventilation or air conditioning?" },
			{ id: "p2q13", html: "Will it thermally throttle under sustained load?" },
			{ id: "p2q14", html: "What are the idle and full-load noise levels?" },
			{ id: "p2q15", html: "Is that noise acceptable day and night in that room?" },
			{ id: "p2q16", html: "How will fans and filters be cleaned over time?" },
		],
	},
	{
		title: "Phase 3: Hardware Capacity and Compatibility",
		questions: [
			{ id: "p3q0", html: "Which CPU/GPU/NPU will actually run inference?" },
			{ id: "p3q1", html: "Does your chosen inference software support that hardware?" },
			{ id: "p3q2", html: "Does the OS support all components?" },
			{ id: "p3q3", html: "If AMD: is the exact GPU supported by the required ROCm version?" },
			{ id: "p3q4", html: "How much RAM/VRAM/unified memory is available after the OS loads?" },
			{ id: "p3q5", html: "How large a model can you load at a given quantization level?" },
			{ id: "p3q6", html: "How much memory does your target context length consume?" },
			{ id: "p3q7", html: "What happens when memory runs out (fallback, slowdown, or crash)?" },
			{ id: "p3q8", html: "Is memory bandwidth high enough for acceptable token speed?" },
			{ id: "p3q9", html: "Has this exact hardware + model combination been benchmarked by others?" },
			{ id: "p3q10", html: "How much storage is needed for models, logs, and backups?" },
			{ id: "p3q11", html: "How quickly will downloaded models fill the drive?" },
			{ id: "p3q12", html: "Does the storage have adequate speed and write endurance?" },
			{ id: "p3q13", html: "Is 2.5GbE/5GbE/10GbE networking supported if needed?" },
			{ id: "p3q14", html: "Can the hardware run continuously within vendor specs?" },
		],
	},
	{
		title: "Phase 4: Local Network Design",
		questions: [
			{ id: "p4q0", html: "How will the server connect -> wired Ethernet or Wi-Fi?" },
			{ id: "p4q1", html: "What cable/switch/port speeds are required?" },
			{ id: "p4q2", html: "Will large model downloads disrupt others' streaming or gaming?" },
			{ id: "p4q3", html: "What are your internet download and upload speeds?" },
			{ id: "p4q4", html: "Does your internet plan have data caps or hosting restrictions?" },
			{ id: "p4q5", html: "Could sustained traffic trigger ISP throttling?" },
			{ id: "p4q6", html: "Does your ISP use CGNAT or give you a public IP?" },
			{ id: "p4q7", html: "Does your public IP change over time?" },
			{ id: "p4q8", html: "How will the server get a stable local IP (DHCP reservation or static)?" },
			{ id: "p4q9", html: "Should the server sit on a separate VLAN to isolate it from personal devices and smart-home gear?" },
			{ id: "p4q10", html: "What firewall rules are needed between segments?" },
			{ id: "p4q11", html: "Will local access still work if the internet goes down?" },
		],
	},
	{
		title: "Phase 5: Operating System and Local Software",
		questions: [
			{ id: "p5q0", html: "Which OS will you install?" },
			{ id: "p5q1", html: "Headless (no desktop) or full desktop?" },
			{ id: "p5q2", html: "Will services run directly on the host, in Docker/Podman, or in VMs?" },
			{ id: "p5q3", html: "Is GPU acceleration supported inside your chosen container setup?" },
			{ id: "p5q4", html: "Which inference engine (Ollama, vLLM, etc.)?" },
			{ id: "p5q5", html: "Does it support your model formats and hardware acceleration?" },
			{ id: "p5q6", html: "Does it expose an OpenAI-compatible API (so standard apps work)?" },
			{ id: "p5q7", html: "Does it support streaming responses?" },
			{ id: "p5q8", html: "Does it support multiple loaded models and concurrent requests?" },
			{ id: "p5q9", html: "Will models stay loaded or unload when idle?" },
			{ id: "p5q10", html: "How long do model swaps/cold starts take?" },
			{ id: "p5q11", html: "Is a local web UI (e.g., Open WebUI) wanted for the family?" },
			{ id: "p5q12", html: "Do you want document Q&A (RAG)? If so, what stores the documents?" },
			{ id: "p5q13", html: "Can everything run fully offline on the local network?" },
			{ id: "p5q14", html: "How will you pin software versions to avoid surprise breakage?" },
			{ id: "p5q15", html: "How will you apply and, if needed, roll back updates?" },
		],
	},
	{
		title: "Phase 6: Models and Model Lifecycle",
		questions: [
			{ id: "p6q0", html: "Which models do you want for each use case?" },
			{ id: "p6q1", html: "Does each model's license permit sharing access with family members over an API?" },
			{ id: "p6q2", html: "Does the license restrict commercial use (relevant if any family member uses it for work)?" },
			{ id: "p6q3", html: "What model sizes/quantizations give acceptable quality and speed?" },
			{ id: "p6q4", html: "From which trusted source will you download models?" },
			{ id: "p6q5", html: "How will you verify downloaded files are genuine and uncorrupted?" },
			{ id: "p6q6", html: "How will family apps reference models -> fixed names or an alias like <code>best-model</code>?" },
			{ id: "p6q7", html: "How will you reassign that alias when you upgrade models?" },
			{ id: "p6q8", html: "How will you test a new model before making it the family default?" },
			{ id: "p6q9", html: "How will you roll back a bad model change?" },
			{ id: "p6q10", html: "How many old models will you keep?" },
			{ id: "p6q11", html: "When and how will you delete unused models to prevent the disk filling up?" },
			{ id: "p6q12", html: "How will you get an alert before storage runs out?" },
		],
	},
	{
		title: "Phase 7: Private Remote Access (Family Away From Home)",
		questions: [
			{ id: "p7q0", html: "Confirmed private-only: no public URL exposed to the open internet?" },
			{ id: "p7q1", html: "Which method: a private mesh VPN (Tailscale/WireGuard) so only enrolled family devices can connect?" },
			{ id: "p7q2", html: "Are you behind CGNAT (which makes a mesh VPN the practical choice)?" },
			{ id: "p7q3", html: "How will each family member's device be enrolled into the VPN?" },
			{ id: "p7q4", html: "How will you remove a lost/stolen device from the VPN?" },
			{ id: "p7q5", html: "What latency does the VPN add to responses?" },
			{ id: "p7q6", html: "Will streaming responses work reliably through the VPN?" },
			{ id: "p7q7", html: "Will it work from cellular networks and other homes' Wi-Fi?" },
			{ id: "p7q8", html: "Will it work from restrictive networks (hotels, schools, workplaces)?" },
			{ id: "p7q9", html: "Do you need a stable address/hostname for the server, or does the mesh provide one?" },
			{ id: "p7q10", html: "Will TLS/encryption be handled by the mesh, or do you need certificates?" },
			{ id: "p7q11", html: "Will the VPN reconnect automatically after a reboot or outage?" },
			{ id: "p7q12", html: "What happens if the VPN provider has an outage?" },
		],
	},
	{
		title: "Phase 8: API and Client Compatibility",
		questions: [
			{ id: "p8q0", html: "Which apps will each family member use to connect?" },
			{ id: "p8q1", html: "Must the endpoint be OpenAI-API compatible so those apps work?" },
			{ id: "p8q2", html: "Which features must be supported (streaming, image upload, etc.)?" },
			{ id: "p8q3", html: "How will each app be configured with its user's key and the server address?" },
			{ id: "p8q4", html: "What maximum prompt/response/upload sizes must be supported?" },
			{ id: "p8q5", html: "What request timeout is appropriate?" },
			{ id: "p8q6", html: "Will clients retry failed requests, and could that duplicate work?" },
			{ id: "p8q7", html: "How will each app behave when the server is offline?" },
		],
	},
	{
		title: "Phase 9: Per-User Keys, Authentication, and Authorization",
		questions: [
			{ id: "p9q0", html: "Where will the authentication layer live -> does Ollama handle keys natively, or do you need a proxy (LiteLLM, Nginx, or similar) in front of it?" },
			{ id: "p9q1", html: "Will you issue exactly one API key per family member (four total)?" },
			{ id: "p9q2", html: "How does a key travel in requests (e.g., <code>Authorization: Bearer &lt;key&gt;</code>)?" },
			{ id: "p9q3", html: "How will you generate strong, unique keys?" },
			{ id: "p9q4", html: "How will you securely deliver each key to each family member?" },
			{ id: "p9q5", html: "Where will each person store their key on their device safely?" },
			{ id: "p9q6", html: "Will keys have expiration dates, or remain valid until revoked?" },
			{ id: "p9q7", html: "Do any users need different permissions (e.g., only you can change models)?" },
			{ id: "p9q8", html: "Should model-management/admin functions be blocked for the four user keys?" },
			{ id: "p9q9", html: "Will the VPN identity <em>and</em> the API key both be required (two layers)?" },
		],
	},
	{
		title: "Phase 10: Key Monitoring, Revocation, and Reissuance",
		questions: [
			{ id: "p10q0", html: "What per-key data will you log (requests, timestamps, source device/IP, token counts)?" },
			{ id: "p10q1", html: "How will you view that log -> a dashboard, a proxy's built-in analytics (e.g., LiteLLM), or manual log review?" },
			{ id: "p10q2", html: "What patterns would signal a compromised key (unusual volume, unfamiliar location, odd hours)?" },
			{ id: "p10q3", html: "Will you set per-key rate limits or usage quotas to cap damage from a leaked key?" },
			{ id: "p10q4", html: "How will you be alerted automatically when a key exceeds normal usage?" },
			{ id: "p10q5", html: "What is the exact procedure to revoke one key immediately without affecting the other three?" },
			{ id: "p10q6", html: "Can revocation take effect without restarting the whole server?" },
			{ id: "p10q7", html: "What is the exact procedure to issue a replacement key to that one person?" },
			{ id: "p10q8", html: "How will you re-deliver the new key securely?" },
			{ id: "p10q9", html: "How will you confirm the old key no longer works after revocation?" },
			{ id: "p10q10", html: "How will you periodically rotate all keys as good hygiene?" },
			{ id: "p10q11", html: "Where might a key accidentally leak (screenshots, chat apps, synced notes, backups) and how will you prevent that?" },
		],
	},
	{
		title: "Phase 11: Security Hardening",
		questions: [
			{ id: "p11q0", html: "Which ports/services are exposed, and can the inference port stay unreachable from the open internet (only via VPN)?" },
			{ id: "p11q1", html: "Will default passwords and sample credentials be removed?" },
			{ id: "p11q2", html: "How will SSH admin access be secured (keys, not passwords)?" },
			{ id: "p11q3", html: "What host firewall rules are required?" },
			{ id: "p11q4", html: "Will all family traffic be encrypted end to end?" },
			{ id: "p11q5", html: "How will you apply OS, driver, and software security updates promptly?" },
			{ id: "p11q6", html: "Will services run as a non-root user with minimal privileges?" },
			{ id: "p11q7", html: "How will you prevent brute-force attempts against keys or SSH?" },
			{ id: "p11q8", html: "Could a malicious or careless prompt trigger local tools, shell access, or read private files? Which tools/plugins will you enable or disable?" },
			{ id: "p11q9", html: "What is your response plan if you suspect a key or the server is compromised?" },
		],
	},
	{
		title: "Phase 12: Privacy and Logging (Family Data)",
		questions: [
			{ id: "p12q0", html: "Will prompts, responses, and uploads be stored, and for how long?" },
			{ id: "p12q1", html: "Can each family member delete their own history?" },
			{ id: "p12q2", html: "Will logs contain sensitive prompt text or just metadata?" },
			{ id: "p12q3", html: "Who (besides you) can see the logs and conversation history?" },
			{ id: "p12q4", html: "Is sensitive stored data encrypted at rest?" },
			{ id: "p12q5", html: "Does any software send telemetry, and can you disable it?" },
			{ id: "p12q6", html: "Do the mesh/VPN or model-download services see any metadata?" },
			{ id: "p12q7", html: "Have the family members consented to your monitoring of usage?" },
		],
	},
	{
		title: "Phase 13: Performance and Load Management",
		questions: [
			{ id: "p13q0", html: "What token speed and first-response time must be met before you consider it usable?" },
			{ id: "p13q1", html: "How does performance hold up with two or more family members at once?" },
			{ id: "p13q2", html: "What happens when requests queue up -> do they wait, or fail?" },
			{ id: "p13q3", html: "Can one very large request block everyone else?" },
			{ id: "p13q4", html: "What prompt/output/upload limits will you set?" },
			{ id: "p13q5", html: "How will you stop a runaway generation?" },
			{ id: "p13q6", html: "Will model downloads or backups interfere with interactive use?" },
		],
	},
	{
		title: "Phase 14: Monitoring, Administration, and Maintenance",
		questions: [
			{ id: "p14q0", html: "Which system metrics will you monitor (CPU, GPU, memory, temperature, disk, network)?" },
			{ id: "p14q1", html: "How will you know if the service fails while you're away?" },
			{ id: "p14q2", html: "Where will alerts be sent, and will they work if home internet is down?" },
			{ id: "p14q3", html: "How long will logs and metrics be kept, and how will you cap their growth?" },
			{ id: "p14q4", html: "How will you administer the server remotely (via the VPN)?" },
			{ id: "p14q5", html: "Can you reboot it remotely if the inference service freezes?" },
			{ id: "p14q6", html: "Which services must auto-start after a reboot, and in what order (network → VPN → auth/proxy → inference)?" },
			{ id: "p14q7", html: "How will failed services restart without looping endlessly?" },
			{ id: "p14q8", html: "Who maintains this, and what happens if that person is unavailable?" },
		],
	},
	{
		title: "Phase 15: Power Failure, Resilience, and Recovery",
		questions: [
			{ id: "p15q0", html: "What happens on a brief power blink versus an extended outage?" },
			{ id: "p15q1", html: "Will the UPS trigger a clean shutdown before the battery dies?" },
			{ id: "p15q2", html: "Will the machine auto-power-on when power returns?" },
			{ id: "p15q3", html: "Will all services (VPN, auth proxy, inference, model loading) recover automatically without you present?" },
			{ id: "p15q4", html: "What happens if the public IP changes during an outage -> does the VPN still reconnect?" },
			{ id: "p15q5", html: "Could an interrupted download or write corrupt data, and how would you detect it?" },
			{ id: "p15q6", html: "What must be backed up (config, the four keys/user records, aliases, conversation history if kept)?" },
			{ id: "p15q7", html: "Where are backups stored, and is at least one copy off-site?" },
			{ id: "p15q8", html: "Can you restore from backup onto new hardware?" },
			{ id: "p15q9", html: "Have you actually tested a restore?" },
			{ id: "p15q10", html: "Do you have any spare parts (drive, PSU, cable) for quick recovery?" },
		],
	},
	{
		title: "Phase 16: Legal and Policy",
		questions: [
			{ id: "p16q0", html: "Does your ISP permit this kind of home hosting, even if private?" },
			{ id: "p16q1", html: "Does your lease/HOA impose relevant restrictions?" },
			{ id: "p16q2", html: "Does each model's license permit your family-shared use?" },
			{ id: "p16q3", html: "Could copyrighted or confidential material be uploaded by family members, and does that matter?" },
			{ id: "p16q4", html: "Are parental controls or age-appropriate restrictions needed for younger users?" },
			{ id: "p16q5", html: "Could remote use while traveling abroad raise any data-crossing-borders concerns?" },
		],
	},
	{
		title: "Phase 17: Final Go-Live Validation",
		questions: [
			{ id: "p17q0", html: "Has the exact hardware + software + model stack been tested together?" },
			{ id: "p17q1", html: "Has local access been tested with the internet disconnected?" },
			{ id: "p17q2", html: "Has remote access been tested over cellular and unfamiliar Wi-Fi?" },
			{ id: "p17q3", html: "Has an unauthorized device been tested and correctly rejected?" },
			{ id: "p17q4", html: "Has revoking one key and issuing a replacement been tested end to end?" },
			{ id: "p17q5", html: "Have per-key rate limits been tested?" },
			{ id: "p17q6", html: "Has recovery from an inference-engine crash been tested?" },
			{ id: "p17q7", html: "Has recovery from a full reboot been tested?" },
			{ id: "p17q8", html: "Has automatic restart after power loss been tested?" },
			{ id: "p17q9", html: "Has UPS shutdown been tested?" },
			{ id: "p17q10", html: "Has a restore from backup been tested?" },
			{ id: "p17q11", html: "Has a bad model update been rolled back successfully?" },
			{ id: "p17q12", html: "Has disk-full behavior been tested?" },
			{ id: "p17q13", html: "Have temperature and noise been measured under sustained real use?" },
			{ id: "p17q14", html: "Have two-plus simultaneous users been tested?" },
			{ id: "p17q15", html: "Have logs been checked to confirm no keys or sensitive data are leaking into them?" },
			{ id: "p17q16", html: "Is your setup, key-management procedure, and recovery process documented so you (or family) can follow it later?" },
			{ id: "p17q17", html: "Are the total cost, maintenance effort, and performance acceptable before you commit?" },
		],
	},
];